package net.programmer.igoodie.tsl.runtime.attribute;

import net.programmer.igoodie.goodies.runtime.GoodieObject;
import net.programmer.igoodie.tsl.context.TSLContext;
import net.programmer.igoodie.tsl.definition.attribute.TSLAttributeGenerator;
import net.programmer.igoodie.tsl.definition.attribute.TSLDecorator;
import net.programmer.igoodie.tsl.definition.attribute.TSLTag;
import net.programmer.igoodie.tsl.parser.token.TSLDecoratorCall;
import net.programmer.igoodie.tsl.parser.token.TSLPlainWord;
import net.programmer.igoodie.tsl.parser.token.TSLToken;
import net.programmer.igoodie.tsl.util.CollectionUtils;

import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

public class TSLAttributeList {

    protected List<TSLAttributeGenerator> generators;
    protected List<GoodieObject> generatedAttributes;

    public TSLAttributeList() {
        this.generators = new LinkedList<>();
        this.generatedAttributes = new LinkedList<>();
    }

    public List<TSLTag> getTags() {
        return Collections.unmodifiableList(generators.stream()
                .filter(generator -> generator instanceof TSLTag)
                .map(generator -> ((TSLTag) generator))
                .collect(Collectors.toList()));
    }

    public List<TSLDecorator> getDecorators() {
        return Collections.unmodifiableList(generators.stream()
                .filter(generator -> generator instanceof TSLDecorator)
                .map(generator -> ((TSLDecorator) generator))
                .collect(Collectors.toList()));
    }

    /* ---------------------------------- */

    public void loadTag(TSLContext context, TSLTag tagDefinition, TSLPlainWord tagName, List<TSLToken> tagArguments) {
        List<TSLToken> tokens = CollectionUtils.flatAll(TSLToken.class, tagName, tagArguments);
        GoodieObject attributes = tagDefinition.generateAttributesWithNamespace(context, tokens);
        this.generators.add(tagDefinition);
        this.generatedAttributes.add(attributes);
    }

    public void loadDecorator(TSLContext context, TSLDecorator decoratorDefinition, TSLDecoratorCall decoratorCall) {
        List<TSLToken> tokens = Collections.singletonList(decoratorCall);
        GoodieObject attributes = decoratorDefinition.generateAttributesWithNamespace(context, tokens);
        this.generators.add(decoratorDefinition);
        this.generatedAttributes.add(attributes);
    }

    /* ---------------------------------- */

//    private boolean removeGenerator(TSLAttributeGenerator generator) {
//        int index = generators.indexOf(generator);
//
//        if (index == -1) {
//            // No attributes were generated by given generator
//            return false;
//        }
//
//        generatedAttributes.remove(index);
//        generators.remove(index);
//        return true;
//    }
//
//    private boolean removeTag(TSLTag tagDefinition) {
//        return removeGenerator(tagDefinition);
//    }
//
//    private boolean removeDecorator(TSLDecorator decoratorDefinition) {
//        return removeGenerator(decoratorDefinition);
//    }

    /* ---------------------------------- */

    public GoodieObject getSquashedAttributes() {
        GoodieObject squashed = new GoodieObject();

        for (GoodieObject attributeContainer : generatedAttributes) {
            for (String attributeName : attributeContainer.keySet()) {
                squashed.put(attributeName, attributeContainer.get(attributeName));
            }
        }

        return squashed;
    }

}
