package net.programmer.igoodie.tsl.runtime.attribute;

import com.google.gson.JsonObject;
import net.programmer.igoodie.tsl.definition.attribute.TSLAttributeGenerator;
import net.programmer.igoodie.tsl.definition.attribute.TSLDecorator;
import net.programmer.igoodie.tsl.definition.attribute.TSLTag;
import net.programmer.igoodie.tsl.parser.token.TSLString;

import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

public class TSLAttributeList {

    protected List<TSLAttributeGenerator> generators;
    protected List<JsonObject> attributeContainers;

    public TSLAttributeList() {
        this.generators = new LinkedList<>();
        this.attributeContainers = new LinkedList<>();
    }

    public List<TSLTag> getTags() {
        return generators.stream()
                .filter(generator -> generator instanceof TSLTag)
                .map(generator -> ((TSLTag) generator))
                .collect(Collectors.toList());
    }

    /* ---------------------------------- */

    public void addTag(TSLTag tagDefinition, TSLString tagToken, List<TSLString> args) {
        JsonObject attributes = tagDefinition.evaluateAttributesWithNamespace(tagToken, args);
        this.generators.add(tagDefinition);
        this.attributeContainers.add(attributes);
    }

    public void addDecorator(TSLDecorator decoratorDefinition, TSLString tagToken, List<TSLString> args) {
        JsonObject attributes = decoratorDefinition.evaluateAttributesWithNamespace(tagToken, args);
        this.generators.add(decoratorDefinition);
        this.attributeContainers.add(attributes);
    }

    /* ---------------------------------- */

    private boolean removeGenerator(TSLAttributeGenerator generator) {
        int index = generators.indexOf(generator);

        if (index == -1) {
            // No attributes were generated by given generator
            return false;
        }

        attributeContainers.remove(index);
        return true;
    }

    private boolean removeTag(TSLTag tagDefinition) {
        return removeGenerator(tagDefinition);
    }

    private boolean removeDecorator(TSLDecorator decoratorDefinition) {
        return removeGenerator(decoratorDefinition);
    }

    /* ---------------------------------- */

    public JsonObject getSquashedAttributes() {
        JsonObject squashed = new JsonObject();

        for (JsonObject attributeContainer : attributeContainers) {
            for (String attributeName : attributeContainer.keySet()) {
                squashed.add(attributeName, attributeContainer.get(attributeName));
            }
        }

        return squashed;
    }

}
